### ISSUE TITLE
Map schema of OE2010 database

### ISSUE THREAD

**Issue by u5561865-drc** [eckersleyalexander/orienteering_live_results#19]

**Comment by ShamelessEnd** [comment]
https://docs.google.com/document/d/1ihVQNub1uEkuXIsuxTGV-sSSBLBIFnD4oSlRWMD9Tcs/edit?usp=sharing

this has all the (non-empty) tables from the demo events and labels on some of the data we need.

the biggest missing thing is exactly how all the time data is being handled. It looks like there are Start/Finish times in Telin.dat, and there are times in Chip1.dat but the overall time from Chip1 doesn't line up with what is saved in Telin

**Comment by ShamelessEnd** [comment]
so using the difference between ChipStemple# tags in the Chip1.dat data i can get splits that match what OE2010 reports spit out. The ChipZiel timestamp is also fine for the finish. The problem is that I dont see anywhere in Chip1.dat where the start tag is being saved - there's space for it but the numbers are junk. ChipCheck is the only other tag that's consistently filled but taking the difference from that and the first checkpoint doesn't give the right split time.
