### ISSUE TITLE
Choose desktop GUI framework

### ISSUE THREAD

**Issue by u5561865-drc** [eckersleyalexander/orienteering_live_results#9]

**Comment by moorecode** [comment]
I've been seeing good things about Avalonia, though it does seem to be WIP https://github.com/AvaloniaUI/Avalonia

**Comment by moorecode** [comment]
There are two other choices, UWP (introduced in win10) and WPF. I think we should go with WPF as it is apparently more robust, has less limitations and will let us support older operating systems in the future. UFW also requires the Windows store or sideloading to work so that should be avoided.

Lets so with WPF, it seems the best option, source: https://github.com/jbe2277/waf/wiki/UWP-vs.-WPF
